### ISSUE TITLE
Let `PermissionsExtractor::extract` receive a `&mut ServiceRequest` so extractors can actually access the inner `HttpRequest`

### ISSUE THREAD

**Issue by alexschrod** [DDtKey/actix-web-grants#16]
As far as I can tell, the only way to get a hold of a `ServiceRequest`'s inner `HttpRequest` is through `into_parts`, which takes `self` and `parts_mut`, which takes `&mut self`. Since actix-web-grants hands you a `&ServiceRequest`, this `HttpRequest` is therefore inaccessible, limiting the usefulness.

**Comment by DDtKey** [comment]
Hi!

It make sense, thank you for your suggestion!

You can do a PR if you want.  Otherwise, I will try to do it as soon as possible 🙂

**Comment by alexschrod** [comment]
One thing to keep in mind is that changing the signature of `GrantsMiddleware::with_extractor` is probably a breaking change. Might be better to add a new one, like `GrantsMiddleware::with_extractor_mut` or something like that, to avoid breaking existing code.

**Comment by DDtKey** [comment]
> One thing to keep in mind is that changing the signature of `PermissionsExtractor::extract` is probably a breaking change. Might be better to add a new one, like `PermissionsExtractor::extract_mut` or something like that, to avoid breaking existing code.

Yeah, you are absolutely right. I have some ideas, but I'm currently on vacation and can't try to implement this with backward compatible 🙁 
But in a week I'll have time

**Comment by DDtKey** [comment]
@alexschrod I have tried to implement this backward compatible. It looks like everything worked out. 
If you want, you can take a look at the PR #17
After the merge, I will also transfer this to the branch for the 3rd version of `actix-web`

**Comment by alexschrod** [comment]
Looks like you removed your message to me about testing it out, but I gave it a go anyway, so with
```toml
actix-web-grants = { version = "3.0.0-beta.2", git = "https://github.com/DDtKey/actix-web-grants.git", rev = "aeb24878487306d45d4059cf1528a97358420902" }
```
in my `Cargo.toml`, I could change my `async fn extract_permissions(request: &ServiceRequest)` to `async fn extract_permissions(request: &mut ServiceRequest)`, and remove my "super safe and totally not UB" solution that I'd been using up until this point, `let mut_request: &mut ServiceRequest = unsafe { &mut *(request as *const _ as *mut _) };` 😅

**Comment by DDtKey** [comment]
> Looks like you removed your message to me about testing it out, but I gave it a go anyway, so with
 
Yeah, sorry (I realized that you should receive a notification about the associated PR) :sweat_smile:
 
 > in my `Cargo.toml`, I could change my `async fn extract_permissions(request: &ServiceRequest)` to `async fn extract_permissions(request: &mut ServiceRequest)`, and remove my "super safe and totally not UB" solution that I'd been using up until this point, `let mut_request: &mut ServiceRequest = unsafe { &mut *(request as *const _ as *mut _) };` 😅

That's great!
Thanks a lot for testing 🙏
