### ISSUE TITLE
Error "type `Config` is not a member of trait `FromRequest`"

### ISSUE THREAD

**Issue by maku** [DDtKey/actix-web-grants#21]
When I try to use "actix-web-grants" I get the following error:

error[E0437]: type `Config` is not a member of trait `FromRequest`
  --> C:\Users\myuser\.cargo\registry\src\github.com-1ecc6299db9ec823\actix-web-grants-3.0.0-beta.3\src\permissions\mod.rs:92:5

What could be the reason to get this error?

**Comment by maku** [comment]
when I am using the latest version from github (unpublished) then the error is gone...

**Comment by Kbman99** [comment]
You should more than like only be using the beta release if you're using the beta release of `actix-web`. But this issue is already fixed by https://github.com/DDtKey/actix-web-grants/pull/20.

If you wish to use it before a new release is cut then you can place this in your `Cargo.toml`:
`actix-web-grants = {  git = "https://github.com/DDtKey/actix-web-grants.git", rev = "0749bb5444d6b523250b0367707eaa7e5878f4c7" }`

**Comment by maku** [comment]
@Kbman99 thanks for answering, but I do not understand. I use actix-web="4.0.0-beta.10", actix-http = "3.0.0-beta.11"

**Comment by Kbman99** [comment]
> @Kbman99 thanks for answering, but I do not understand. I use actix-web="4.0.0-beta.10", actix-http = "3.0.0-beta.11" and actix-web-grants = "3.0.0-beta.3"

Yeah the import of `actix-web-grants = “3.0.0-beta.3”` is broken and will not work with the latest changes in the beta releases of the other actix projects. You need to replace your import of the broken `actix-web-grants` with what I pasted above.

**Comment by DDtKey** [comment]
@maku as it was already said, #20 changes are required to work  correctly with `actix-web: 4.0.0-beta.10`. But it's not included to `actix-web-grants: 3.0.0-beta.3`. I going to publish `beta.4` soon with these changes.

actix-web 4 beta changes can be without backward compatibility. Just try the version from git or wait the new version of `actix-web-grants`

**Comment by DDtKey** [comment]
@maku I just have published v3.0.0-beta.4 version with `actix-web 4.0.0-beta.11` support. So, you can use version from crates.io now 🙂

**Comment by maku** [comment]
@DDtKey great,  thank you very much
