### ISSUE TITLE
New release with Actix Web 4 support

### ISSUE THREAD

**Issue by Chaostheorie** [DDtKey/actix-web-grants#31]
I would like to request a new major release (3.0.0) with support for the stabilized Actix Web 4.0. Most of the work for such a release has already been done, with the changes added in `3.0.0-beta.x`. The required changes have been done in #30. 

PS:
Thank you for your awesome work on Actix Web grants. I've recently started to use Actix Web  for a personal project, and the permission guarding with the grant macros was very helpful for getting everything started.

**Comment by DDtKey** [comment]
Thank you very much! 👍 
I've published the stable version!

**Comment by Chaostheorie** [comment]
Thank you for the fast response and release.
