### ISSUE TITLE
Validator issue

### ISSUE THREAD

**Issue by maxidev** [DDtKey/actix-web-grants#36]
Hi there, seems that the old exaple does not compile due to mismatch return types, specifically here:
https://github.com/DDtKey/actix-web-grants/blob/92d97c9bebb4b42beff62e829ca6b3e64edbb75b/examples/jwt-httpauth/src/main.rs#L50

**Comment by DDtKey** [comment]
That's just example with `actix-web-httpauth v0.6.0` and it works/compiles. 

You probably trying to do the same with newest version (> 0.7.0). [Link to changes](https://github.com/actix/actix-extras/blob/master/actix-web-httpauth/CHANGES.md#070---2022-07-19).

I've updated example to use `0.8.0` version of `httpauth` 🙂

**Comment by maxidev** [comment]
Thank you so much, your JWT example with httpauth is by far the best one out there.

**Comment by DDtKey** [comment]
I'm glad to hear it 😅
