### ISSUE TITLE
Allow some routes to non authenticated users?

### ISSUE THREAD

**Issue by jb-alvarado** [DDtKey/actix-web-grants#38]
Hello,
this is a bit related to #37. Sometimes there are routes in the same scope, but some of them need authentication and some not. 

Is there a strait way in `actix-web-grants`  to implement this? My idea was, to map all users which send requests without authentication header to role **Guest** and use this in the route as:

```Rust
#[has_any_role("Role::Admin", "Role::Guest", type = "Role")]
#[get("/my_route/")]
async fn my_route( ...
```

My only solution is s very bad workaround:

```Rust
async fn validator(req: ServiceRequest, credentials: BearerAuth) -> Result<ServiceRequest, Error> {
    match auth::decode_jwt(credentials.token()).await {
        Ok(_) => req.attach(vec![Role::Admin]),
        Err(e) => {
            error!("validation: {e}");
            req.attach(vec![Role::Guest])
        }
    };
    req.attach(vec![Role::Admin]);

    Ok(req)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
   HttpServer::new(move || {
            let auth = HttpAuthentication::bearer(validator);

            App::new()
                .wrap_fn(|mut req, srv| {
                    if req.headers().get("authorization").is_none() {
                        req.headers_mut().append(
                            actix_web::http::header::HeaderName::from_static("authorization"),
                            actix_web::http::header::HeaderValue::from_static("Bearer guest"),
                        );
                    }
                    srv.call(req).map(|res| res)
                })
                .service(
                    web::scope("/api/v2")
                        .wrap(auth)
                        .service(my_route)
                        ...
```

is there a better way to solve the problem here?

**Comment by DDtKey** [comment]
I've took a look at the reasons, and it looks like issue with `actix-web-httpauth`. It extracts header before `validator` will be called 🤔 
I just mean that it's relevant only for integration with external crates. With `actix-web-grants` it's possible to define custom logic

Have you tried `HttpAuthentication::with_fn(validator)` and define validator fn with `Option<BearerAuth>` instead of just `BearerAuth`?

In this way it should be possible to handle empty header and mark user as Guest.

**Comment by jb-alvarado** [comment]
Thank you very much! With `HttpAuthentication::with_fn(validator)` it is possible! Now I only use the validator function like:

```Rust
async fn validator(
    req: ServiceRequest,
    credentials: Option<BearerAuth>,
) -> Result<ServiceRequest, Error> {
    match credentials {
        Some(credit) => {
            auth::decode_jwt(credit.token()).await?;
            req.attach(vec![Role::Admin]);
        }
        None => {
            req.attach(vec![Role::Guest]);
        }
    }

    Ok(req)
}
```
