### ISSUE TITLE
use enum in attribute?

### ISSUE THREAD

**Issue by peteringram0** [DDtKey/actix-web-grants#39]
Hi,

Is it possible to use an enum value in the has_permissions attribute at all? I understand that what i have below is not valid syntax but want to understand if something like this is possible?

from:
````rust
#[has_permissions("CanRead")]
````

to:
````rust
#[has_permissions(Permissions::CanRead.to_string())]
````

**Comment by DDtKey** [comment]
Well, I'm gonna do some refactoring soon with one more feature. 
So 'll try to change it to `expression` instead of only `string` 🤔

**Comment by DDtKey** [comment]
Btw, I probably misunderstood the initial question. Have you checked [this example (/examples/enum-role)](https://github.com/DDtKey/actix-web-grants/blob/main/examples/enum-role/src/main.rs)? 

It's currently possible to use enums, but you need to pass their path as strings `"MySuperEnum::User"`
