### ISSUE TITLE
Question: Use multiple proc macros at the same time

### ISSUE THREAD

**Issue by DaveKram** [DDtKey/actix-web-grants#40]
More of a question than an issue.

Was hoping to do something like the following:

`#[get("/read")]
#[has_permissions("UserPermissions::UserRead")]
#[has_any_role("UserRole::Admin", "UserRole::User")]`

where I can check 2 different types (a UserPermissions enumeration and a UserRole enumeration on a singular endpoint.

Aka, I'd like for the permission to be UserRead, but also the user's role to be either an Admin or a User. 

Given the 2 approaches to macros (has or has_any), I can't shove all of these into the same enumeration to solve this? (since the has_permissions/has_roles would exclude the 'or' logic for the roles, and has_any_role/has_any_permission, would just return true if any one is true.

And so far what I can see, the has_any_role/has_roles proc macros are the same logic as the permissions ones, just looking for a ROLES_ prefix in the string.

Trying to do the above on a struct provides me with:

`identifier `_auth_details_` is bound more than once in this parameter list
used as parameter more than once`

Am I going about this/thinking about this wrong? I'd like to have a user role AND set of associated permissions checked.

**Comment by DDtKey** [comment]
Hi @DaveKram and thanks for reporting!

It's kind of related with this feature-request for rocket's version: https://github.com/DDtKey/rocket-grants/issues/3
In general, I'm going to do some large refactoring (merging crates into single repo, implement that feature and minor ones). However because of my bandwidth I'm not sure about timeline. 

But for now, I agree, need to support multiple macros at the same time, it sounds reasonable.

**Comment by DaveKram** [comment]
@DDtKey thanks for the response. Totally understandable. 

If I can also find time past my day job, I may investigate it a little. 

Thanks for the work you do though, the crate has been useful otherwise. I'll close this out for now.

**Comment by DDtKey** [comment]
I don't mind leaving it open, maybe I'll look into it over the weekend.

**Comment by DDtKey** [comment]
@DaveKram could you try a new version (`3.0.2`)?

**Comment by DaveKram** [comment]
@DDtKey thanks for taking a look at this! I've updated my code that was using that/testing all the roles/perms iteratively making REST calls to my endpoints, and it seems to work fine. No issues to report.
