### ISSUE TITLE
404 instead of 403 for Scope

### ISSUE THREAD

**Issue by RoDmitry** [DDtKey/actix-web-grants#7]
I know it's not a documented use case, but it works and somehow returns 404 error instead of 403.
```rust
.service(
    web::scope("/admin")
        .service(index)
        .service(users)
        .guard(PermissionGuard::new(ROLE_ADMIN.to_string()))
);
```
Was checked on v3.0.0-beta.1

**Comment by RoDmitry** [comment]
And the way it returns errors, I think it's double checking roles in this example:
```rust
use actix_web::{
    get,
    web,
    web::ServiceConfig,
    Responder,
    HttpResponse,
};
use actix_web_grants::{
    proc_macro::has_permissions,
    PermissionGuard,
};

const ROLE_ADMIN: &str = "ROLE_ADMIN";

#[get("")]
// I know I can type #[has_permissions("ROLE_ADMIN")] on every function, instead of .guard
async fn index() -> impl Responder {
    HttpResponse::Ok().body("index")
}

#[get("/users")]
#[has_permissions("ROLE_SUPER_ADMIN")]
async fn users() -> impl Responder {
    HttpResponse::Ok().body("users")
}

// --------------------- Paths config ------------------------
pub fn configure(cfg: &mut ServiceConfig) {
    cfg
        .service(
            web::scope("/admin")
                .service(index)
                .service(users)
                .guard(PermissionGuard::new(ROLE_ADMIN.to_string()))
        );
}

```
At first it checks if you have `ROLE_ADMIN`, and then if you are also `ROLE_SUPER_ADMIN`. Is that possible to avoid double checking, and prioritize on the function's `#[has_permissions()]`?

**Comment by DDtKey** [comment]
> I know it's not a documented use case, but it works and somehow returns 404 error instead of 403.
> 
> ```rust
> .service(
>     web::scope("/admin")
>         .service(index)
>         .service(users)
>         .guard(PermissionGuard::new(ROLE_ADMIN.to_string()))
> );
> ```
> 
> Was checked on v3.0.0-beta.1

Yes it is, the reason is in the way `Guard` is processed by the `actix-web` itself (it only expects a `bool`)
[actix guard doc](https://docs.rs/actix-web/3.0.0/src/actix_web/guard.rs.html)

**Comment by RoDmitry** [comment]
So is it just a misuse or it could be fixed? I mean the error code and the double checking.

**Comment by DDtKey** [comment]
> At first it checks if you have `ROLE_ADMIN`, and then if you are also `ROLE_SUPER_ADMIN`. Is that possible to avoid double checking, and prioritize on the function's `#[has_permissions()]`?

You can separate services (or scopes), for example: 
```rust
    cfg
        .service(
            web::scope("/admin")
                .service(web::to(index).guard(PermissionGuard::new(ROLE_ADMIN.to_string())))
                .service(users)             
        );
```

But combining them on the same `services`/`scopes` will check for both. `Guard` is more primary.

**Comment by DDtKey** [comment]
> So is it just a misuse or it could be fixed? I mean the error code and the double checking.

The HTTP code in the case of `Guard` is the expected behavior. This can be used if you are satisfied with the `404` code.
In general, many people prefer to use `404` error codes instead of `403` in such cases.

**Comment by RoDmitry** [comment]
So the only way to avoid double checking is repeating `PermissionGuard` for each `service`, because of how `actix-web` handles it, right?

**Comment by RoDmitry** [comment]
> many people prefer to use 404 error

That's strange. I wouldn't. How do I change it to return `403`?

**Comment by DDtKey** [comment]
> So the only way to avoid double checking is by repeating `PermissionGuard` for each `service` in `scope`, because of how `actix-web` handles it, right?

Not necessary for every, you can combine a set of services with a common scope and one `PermissionGuard` 🤔 

Also you can use only a macro (on each handler) `#[has_permissions(...)`

**Comment by DDtKey** [comment]
> > many people prefer to use 404 error
> 
> That's strange. I wouldn't. How do I change it to return 403? Avoid using it for scopes I guess?

I'm afraid the `Guard` mechanism does not allow us to override the response code 🙁 
Actix guards only return `404` or allow access to the resource

So yeah, for now, the best solution would be to use a macro or manual check (of your choice)

**Comment by RoDmitry** [comment]
But `PermissionGuard` for each `service` or macro - return `403`, except `PermissionGuard` on `Scope`. How so?

**Comment by DDtKey** [comment]
> But `PermissionGuard` for each `service` or macro - return `403`, except `PermissionGuard` on `Scope`. How so?

Macro return `403` - it's defined by current lib. 
But `PermissionGuard` always should return `404` as I know. Are you sure?  🤔 
As [in the example](https://github.com/DDtKey/actix-web-grants/blob/ba717de4bd3f0ed9b390095227445f0a45a2612f/examples/base_example.rs#L41), if we change the role in the guard, it will return `404`

**Comment by RoDmitry** [comment]
I thought it's the same, need to check

**Comment by DDtKey** [comment]
This is good point 👍 
I think need to describe this behavior in the documentation and readme (regarding the response code) 🤔

**Comment by RoDmitry** [comment]
Yeah, my bad, I didn't check. Попутал немного ☺.

**Comment by RoDmitry** [comment]
> This is good point 👍
> I think need to describe this behavior in the documentation and readme (regarding the response code) 🤔

Would be great and very useful for newcomers.

**Comment by RoDmitry** [comment]
Maybe there is a possibility to pass something to get `403` as macro does?

**Comment by DDtKey** [comment]
> Maybe there is a possibility to pass something to get `403` as macro does?

I will study this question a little later, and if possible, we will definitely do it at the library level.
But at the moment, I do not know about such a possibility 🙁

**Comment by RoDmitry** [comment]
I found out how `Guards` work, and I found the way to send whatever you want. You just can make another service, with the same link, easy)

**Comment by DDtKey** [comment]
> I found out how `Guards` work, and I found the way to send whatever you want. `Guard` just checks whether that service suits some conditions or not, and in that case just skips it. You can just make another service, with the same link, easy) [Check it out](https://github.com/DDtKey/actix-web-grants/commit/3da6a87550a423829ee3dd156c34e72b97b40310). Is that enough?

Guards can really only be used for routing purposes.

So, yeap, this option will work. 
Unfortunately this looks like a workaround (not very convenient), but perhaps this is the only option that we have for the `Guard` way.

**Comment by RoDmitry** [comment]
Do you need this? #9

**Comment by DDtKey** [comment]
> Do you need this? #9 I mean is that the way to update readme?)

I would like to add this, thanks 🙂

**Comment by RoDmitry** [comment]
We forgot about `Scope`. Check here #10

**Comment by RoDmitry** [comment]
Regex takes `/admin2` also, maybe it needs some fixes 🤔
