### ISSUE TITLE
Redirect to another page if not granted instead of error page

### ISSUE THREAD

**Issue by RoDmitry** [DDtKey/actix-web-grants#8]
I know I can make the redirect manually, but I think it's possible to make a redirect look good in macro, something like that:
`#[has_permissions("ROLE_ADMIN", redirect = "/login")]`

[That](https://github.com/DDtKey/actix-web-grants/blob/8373a5e7130fef0253d709480cc28f06d8a5ed33/proc-macro/src/expand.rs#L70) is the response, right? We can make a redirect there, if it was passed in macro. Does it make sense?

Upd: I guess not, that's repeating. We need middleware for that I guess.

**Comment by DDtKey** [comment]
Interesting idea
I think this can be implemented, but as a rule it is needed globally for the project, and not for a specific endpoint 🤔
